resources:
  jobs:
    dpe_project:
      name: dpe_project
      tasks:
        - task_key: mount
          notebook_task:
            notebook_path: /Repos/fcompagnoni@myges.fr/cloud_ml_databricks/databricks_notebooks/mount
            source: WORKSPACE
          job_cluster_key: Job_cluster
        - task_key: data-prep
          depends_on:
            - task_key: mount
          notebook_task:
            notebook_path: /Repos/fcompagnoni@myges.fr/cloud_ml_databricks/databricks_notebooks/data_preparation
            source: WORKSPACE
          job_cluster_key: Job_cluster
        - task_key: data-viz
          depends_on:
            - task_key: data-prep
          notebook_task:
            notebook_path: /Repos/fcompagnoni@myges.fr/cloud_ml_databricks/databricks_notebooks/data_vizualisation
            source: WORKSPACE
          job_cluster_key: Job_cluster
        - task_key: train
          depends_on:
            - task_key: data-viz
          notebook_task:
            notebook_path: /Repos/fcompagnoni@myges.fr/cloud_ml_databricks/databricks_notebooks/train_automl
            source: WORKSPACE
          job_cluster_key: Job_cluster
        - task_key: api_call
          depends_on:
            - task_key: train
          notebook_task:
            notebook_path: /Repos/fcompagnoni@myges.fr/cloud_ml_databricks/databricks_notebooks/api_documentation_and_examples
            source: WORKSPACE
          job_cluster_key: Job_cluster
      job_clusters:
        - job_cluster_key: Job_cluster
          new_cluster:
            cluster_name: ""
            spark_version: 13.3.x-scala2.12
            azure_attributes:
              first_on_demand: 1
              availability: ON_DEMAND_AZURE
              spot_bid_max_price: -1
            node_type_id: Standard_DS3_v2
            spark_env_vars:
              PYSPARK_PYTHON: /databricks/python3/bin/python3
            enable_elastic_disk: true
            data_security_mode: LEGACY_SINGLE_USER_STANDARD
            runtime_engine: PHOTON
            num_workers: 8
